config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: %i[index show]

  namespace :vender do
    resources :products
    resources :orders, only: %i[index show]
  end

  namespace :users do
    resources :orders, only: %i[index show destroy]
  end
  
  get '/sellers/profile', to: 'sellers#profile', as: 'seller_profile'
  get '/users/profile',   to: 'users#profile',   as: 'user_profile'

  post '/products/:id/favorite', to: 'wishlists#index', as: 'product_favorite'
  get '/favorite', to: 'wishlists#show', as: 'show_favorite'
  delete '/favorite/:id', to: 'wishlists#destroy', as: 'destroy_favorite'

  get '/products/:id/:seller_product_variant_id/order', to: 'order#index', as: 'order'
  get '/products/:id/:seller_product_variant_id/order/payment', to: 'order#payment', as: 'order_payment'
  post '/products/:id/:seller_product_variant_id/order', to: 'order#create'
  get '/products/:id/:seller_product_variant_id/order/confirm', to: 'order#confirmation', as: 'order_payment_confirm'

  root to: 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :description, :available, presence: true
  belongs_to :brand
  has_many :product_variants
  has_many :colors, through: :product_variants
  has_many :displays, through: :product_variants
  has_many :processors, through: :product_variants
  has_many :storages, through: :product_variants

  has_many :product_categories, dependent: :delete_all
  has_many :categories, through: :product_categories

  has_many :seller_products
  has_many :sellers, through: :seller_products
  has_many :wishlists
  has_many_attached :mobile_photos
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# :nodoc:
class ProductsController < ApplicationController
  before_action :set_product, only: :show

  def index
    @products = Product.all.order(:description).page(params[:page]).per(20)
    if (params[:price_min] && params[:price_max]).present?
      @price_min = params[:price_min].to_i
      @price_max = params[:price_max].to_i
      @products = Product.joins(:product_variants).where('price >= ? AND price <= ?', @price_min, @price_max).order(:description).page(params[:page]).per(20)
    end
    if params[:search].present?
      @products = Product.joins(:brand, :categories, :colors, :storages, :processors).where('brands.name LIKE ? OR categories.name LIKE  ? OR colors.name LIKE ? OR storages.name LIKE ? OR processors.name LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").distinct.page(params[:page]).per(20)
    end
    @brand_ids = []
    if params[:brand_id].present?
      @brand_ids = params[:brand_id].split(',')
      @products = @products.where(brand_id: @brand_ids).order(:description).page(params[:page]).per(20)
    end
    @category_ids = []
    if params[:category_id].present?
      @category_ids = params[:category_id].split(',')
      @products = Product.includes(:product_categories).where(product_categories: { category_id: @category_ids }).order(:description).page(params[:page]).per(20)
    end
    @processor_ids = []
    if params[:processor_id].present?
      @processor_ids = params[:processor_id].split(',')
      @products = Product.includes(:product_variants).where(product_variants: { processor_id: @processor_ids }).order(:description).page(params[:page]).per(20)
    end
    @color_ids = []
    if params[:color_id].present?
      @color_ids = params[:color_id].split(',')
      @products = Product.includes(:product_variants).where(product_variants: { color_id: @color_ids }).order(:description).page(params[:page]).per(20)
    end
    @display_ids = []
    if params[:display_id].present?
      @display_ids = params[:display_id].split(',')
      @products = Product.includes(:product_variants).where(product_variants: { display_id: @display_ids }).order(:description).page(params[:page]).per(20)
    end
    @storage_ids = []
    if params[:storage_id].present?
      @storage_ids = params[:storage_id].split(',')
      @products = Product.includes(:product_variants).where(product_variants: { storage_id: @storage_ids }).order(:description).page(params[:page]).per(20)
    end
  end

  def show
    @price = ProductVariant.where(product_id: params[:id]).pluck(:price)
    @wishlist = current_user.wishlists.find_by(product_id: params[:id]) if user_signed_in?
  end

  private

  def set_product
    @product = Product.find_by(id: params[:id])
  end

  def product_params
    params.require(:product).permit(:description, :available, :release_year,
                                    :brand_id, mobile_photos: [])
  end
end

app/controllers/vender/order_controller.rb
module Vender
  # :nodoc:
  class OrderController < ApplicationController
    before_action :authenticate_seller!
    def index
      @order = current_seller.orders.all
    end
  end
end

app/controllers/vender/orders_controller.rb
# frozen_string_literal: true

module Vender
  # :nodoc:
  class OrdersController < ApplicationController
    before_action :authenticate_seller!
    def index
      @order = current_seller.orders.all
    end

    def show
      @order = Order.find_by(id: params[:id])
    end
  end
end

app/controllers/vender/products_controller.rb
# frozen_string_literal: true

module Vender
  # :nodoc:
  class ProductsController < ApplicationController
    before_action :authenticate_seller!
    before_action :set_seller_product, only: %i[show edit update destroy]

    def index
      @vender_products = current_seller.seller_products.page(params[:page]).per(20)
    end

    def show; end

    def new
      @product_variant = Product.find_by(id: params[:product_id])
      @vender_product = current_seller.seller_products.new(product_id: params[:product_id])
    end

    def edit
      @product_variant = @vender_product.product
    end

    def create
      @vender_product = current_seller.seller_products.new(seller_product_params)
      respond_to do |format|
        if @vender_product.save
          format.html { redirect_to vender_products_url, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: vender_products_url }
        else
          format.html { render :new }
          format.json { render json: @vender_product.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @vender_product.update(seller_product_params)
          format.html { redirect_to vender_products_url, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: vender_products_url }
        else
          format.html { render :edit }
          format.json { render json: @vender_product.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @vender_product.destroy
      respond_to do |format|
        format.html { redirect_to vender_products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_seller_product
      @vender_product = SellerProduct.find_by(id: params[:id])
    end

    def seller_product_params
      params.require(:seller_product).permit(:product_id, :seller_id,
                                             seller_product_variants_attributes:
                                             %i[id product_variant_id price
                                                discount final_price _destroy])
    end
  end
end

app/views/vender/products/_form.html.haml
%br/
%br/
.container
  = form_for @vender_product, url: (%w[new create].include?(action_name) ? vender_products_path : vender_product_path) do |f|
    - if f.object.new_record?
      %h6 Product
      = f.select :product_id, options_for_select(Product.all.collect{ |p| [p.description, p.id] }, f.object.product_id),
        {prompt: "select product"},class: "form-control", onchange: "show_product_form(this);"
    - else
      %h5= @vender_product.product.description
    %br/
    - if @product_variant.present?
      #seller_product_variants
        = f.fields_for :seller_product_variants do |seller_product_variant|
          = render 'seller_product_variant_fields', f: seller_product_variant
        .links
          = link_to_add_association 'Add Variant', f, :seller_product_variants, class: "btn btn-success"
        %br/
      = f.submit "Create", class: "btn btn-success"

:javascript
  function show_product_form(ele) {
    console.log($(ele).val());
    window.location.href = window.location.href.replace(/\?.+/, '') + '?product_id=' + $(ele).val();
  }

app/views/vender/products/_seller_product_variant_fields.html.haml
.nested-fields
  .card.nestedform
    %h6 Product Variant
    = f.select :product_variant_id, options_from_collection_for_select(@product_variant.product_variants, :id, :name), { prompt: true }, class: "custom-select mb-3"
    .form-group.row
      .col-sm-3
        .form-check-label Price
        = f.number_field :price, onblur: "calculate_finalprice(this);", class: "form-control"
      .col-sm-3
        .form-check-label Discount
        = f.number_field :discount, onblur: "calculate_finalprice(this);", class: "form-control"
      .col-sm-3
        .form-check-label Final Price
        = f.text_field :final_price, onblur: "calculate_finalprice(this);", class: "form-control"
    = link_to_remove_association fa_icon("trash"), f, class: "remove"
:javascript
  function calculate_finalprice(ele){
    var ids = ele.id;
    var name = ids.split("_");
    var element = name[7];
    var value = element.value;

    console.log(value);

    }

app/views/vender/products/edit.html.haml
= render 'form'
%br/
.container
  = link_to 'Back', vender_products_path, class: "btn btn-success"

app/views/vender/products/index.html.haml
.row
  .container
    - if @vender_products.empty?
      .text-center
        .card.card-light
          %h5 No products yet ! Would you like to add product?
          .container
            = link_to 'Add product', new_vender_product_path, class: "btn btn-success"
    - else
      .container
        .row
          .card.sellerproduct
            .card-header
              My Product
            .card-body
              - @vender_products.each do |vender_product|
                .row
                  .col-3
                    = image_tag(vender_product.product.mobile_photos.first, width: "100px", height: "150px")
                  .col-7
                    = vender_product.product.description
                    %br/
                    = vender_product.product.brand.name
                    %br/
                    - vender_product.product.product_categories.each do |product_category|
                      = product_category.category.name
                  .col-2
                    .icon-size
                      = link_to fa_icon("eye 10px"), vender_product_path(vender_product)
                      = link_to fa_icon("pencil-square-o 10px"), edit_vender_product_path(vender_product)
                      = link_to fa_icon("trash 10px red"), vender_product_path(vender_product), method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-delete"
                  %hr/


    .pagination.justify-content-center
      = paginate @vender_products

app/views/vender/products/new.html.haml
= render 'form'
%br/
.container
  = link_to 'Back', vender_products_path, class: "btn btn-success"

app/views/vender/products/show.html.haml
.row
  .col-sm-5
    .card
      .row
        .col-sm-4
          .product
            - if @vender_product.product.mobile_photos.attached?
              - @vender_product.product.mobile_photos.each do |mobile_photo|
                .col-2
                  = image_tag(mobile_photo, size: "80", onclick: "set_image(this);",class:"list-group-item")
        .col-sm-6
          .container
            - if @vender_product.product.mobile_photos.attached?
              = image_tag(@vender_product.product.mobile_photos.first, style: "width:100%", class: "hide")
              %img{ id: "expandedImg" ,style: "width:100%"}
    .container
      = link_to 'Back', vender_products_path, class: "btn btn-success"
  .col-sm-7
    %h4= @vender_product.product.description
    %h4= @vender_product.product.brand.name
    - @vender_product.product.product_categories.each do |category|
      = category.category.name
    .row
      .card.showproduct
        .card-header
          Variant Details
        .card-body
          - @vender_product.seller_product_variants.each do |seller_product_variant|
            = seller_product_variant.product_variant.color.name
            ,
            = seller_product_variant.product_variant.processor.name
            ,
            = seller_product_variant.product_variant.storage.name
            ,
            = seller_product_variant.product_variant.display.name
            ,
            = seller_product_variant.product_variant.width
            cm,
            = seller_product_variant.product_variant.height
            cm,
            = seller_product_variant.product_variant.thickness
            mm,
            = seller_product_variant.product_variant.weight
            gram,
            = seller_product_variant.product_variant.rear_camera
            MP,
            = seller_product_variant.product_variant.front_camera
            MP
            %br/

            .form-group.row

              .col-2
                %strong.text-success Price
                = seller_product_variant.price
              .col-2
                %strong.text-success Discount
                = seller_product_variant.discount
                '%
              .col-3
                %strong.text-success Final Price
                = seller_product_variant.final_price

:javascript
  function set_image(imgs){
    $(".hide").hide();
    var expandImg = document.getElementById("expandedImg");
    expandImg.src = imgs.src;
    expandImg.parentElement.style.display = "block";
  }