config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: %i[index show]

  namespace :vender do
    resources :products
    resources :orders, only: %i[index show]
  end

  namespace :users do
    resources :orders, only: %i[index show destroy]
  end
  
  get '/sellers/profile', to: 'sellers#profile', as: 'seller_profile'
  get '/users/profile',   to: 'users#profile',   as: 'user_profile'

  post '/products/:id/favorite', to: 'wishlists#index', as: 'product_favorite'
  get '/favorite', to: 'wishlists#show', as: 'show_favorite'
  delete '/favorite/:id', to: 'wishlists#destroy', as: 'destroy_favorite'

  get '/products/:id/:seller_product_variant_id/order', to: 'order#index', as: 'order'
  get '/products/:id/:seller_product_variant_id/order/payment', to: 'order#payment', as: 'order_payment'
  post '/products/:id/:seller_product_variant_id/order', to: 'order#create'
  get '/products/:id/:seller_product_variant_id/order/confirm', to: 'order#confirmation', as: 'order_payment_confirm'

  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  after_save :email_processing
  validates :address, :city, :state, :pincode, presence: true
  belongs_to :seller
  belongs_to :user
  belongs_to :seller_product_variant
  belongs_to :product_variant

  def email_processing
    OrderJob.perform_later(user_id, seller_id)
  end
end

app/controllers/order_controller.rb
# frozen_string_literal: true

# :nodoc:
class OrderController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[index payment confirmation]

  def index; end

  def payment
    @seller = SellerProductVariant.find_by(id: params[:seller_product_variant_id])
    @order = current_user.orders.new(seller_id: @seller.seller_product.seller_id, product_variant_id: @seller.product_variant_id, price: @seller.price, discount: @seller.discount, final_price: @seller.final_price, seller_product_variant_id: params[:seller_product_variant_id])
  end

  def create
    @order = current_user.orders.new(order_params)
    @order.ordered_date = Time.now
    if @order.save
      redirect_to order_payment_confirm_path
    else
      render action: 'payment'
    end
  end

  def confirmation
    @order = current_user.orders.where(seller_product_variant_id: params[:seller_product_variant_id]).last
  end

  private

  def set_order
    @product = Product.find_by(id: params[:id])
    @seller_product_variant = SellerProductVariant.where(id: params[:seller_product_variant_id])
  end

  def order_params
    params.require(:order).permit(:user_id, :seller_id,
                                  :seller_product_variant_id,
                                  :product_variant_id, :price, :discount,
                                  :final_price, :address, :city, :state,
                                  :pincode, :ordered_date, :shipping_date,
                                  :cancle_date, :payment_type,
                                  :payment_transaction)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.where(id: params[:id])
    @seller_product_variants = SellerProductVariant.where(id: params[:seller_product_variant_id])
  end

  def payment
    @products = Product.where(id: params[:id])
    @seller_product_variants = SellerProductVariant.where(id: params[:seller_product_variant_id])
    @product_variant = ProductVariant.joins(:seller_product_variants).where(seller_product_variants: { id: params[:seller_product_variant_id] })
    @seller = SellerProductVariant.find_by(params[:seller_product_variant_id])

    @order = current_user.orders.new(seller_id: @seller.seller_product.seller_id, product_variant_id: @product_variant.ids, price: @seller.price, discount: @seller.discount, final_price: @seller.final_price, seller_product_variant_id: params[:seller_product_variant_id])
  end

  def order
    @order = current_user.orders.all
  end
  def show
    @orders = Order.find_by(id: params[:id])

  end
  def create
    @order = current_user.orders.new(order_params)
    @order.ordered_date = Time.now

    if @order.save
      redirect_to order_payment_confirm_path
    else
      render action: 'payment'
    end

  end

  def confirmation
    @products = Product.where(id: params[:id])
    @seller_product_variants = SellerProductVariant.where(id: params[:seller_product_variant_id])
    @product_variant = ProductVariant.joins(:seller_product_variants).where(seller_product_variants: { id: params[:seller_product_variant_id] })
  end

  def destroy
    @order = Order.find_by(id: params[:id])
    @order.destroy
    redirect_to order_path
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :seller_id, :seller_product_variant_id, :product_variant_id, :price, :discount, :final_price, :address, :city, :state, :pincode, :ordered_date, :shipping_date, :cancle_date, :payment_type, :payment_transaction)
  end
end

app/controllers/users/orders_controller.rb
module Users
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
      @order = current_user.orders.all
    end

    def show
      @orders = Order.find_by(id: params[:id])
      @time = Time.at(@orders.ordered_date).strftime("%B %e, %Y at %I:%M %p")
    end

    def destroy
      @order = Order.find_by(id: params[:id])
      @order.destroy
      redirect_to users_orders_path
    end

    private

    def order_params
      params.require(:order).permit(:user_id, :seller_id, :seller_product_variant_id, :product_variant_id, :price, :discount, :final_price, :address, :city, :state, :pincode, :ordered_date, :shipping_date, :cancle_date, :payment_type, :payment_transaction)
    end
  end
end

app/controllers/vender/order_controller.rb
module Vender
  # :nodoc:
  class OrderController < ApplicationController
    before_action :authenticate_seller!
    def index
      @order = current_seller.orders.all
    end
  end
end

app/controllers/vender/orders_controller.rb
# frozen_string_literal: true

module Vender
  # :nodoc:
  class OrdersController < ApplicationController
    before_action :authenticate_seller!
    def index
      @order = current_seller.orders.all
    end

    def show
      @order = Order.find_by(id: params[:id])
    end
  end
end

app/views/order/confirmation.html.haml
%h5.text-center Thank You. Your order is confirm
.row
  .col-sm-5
    .card
      .row
        .col-sm-4
          .product
            - if @order.product_variant.product.mobile_photos.attached?
              - @order.product_variant.product.mobile_photos.each do |mobile_photo|
                .col-2
                  = image_tag(mobile_photo, size: "80", onclick: "set_image(this);",class:"list-group-item")
        .col-sm-6
          .container
            - if @order.product_variant.product.mobile_photos.attached?
              = image_tag(@order.product_variant.product.mobile_photos.first, style: "width:100%", class: "hide")
              %img{ id: "expandedImg" ,style: "width:100%"}
  .col-sm-7
    %h4= @order.product_variant.product.description
    %h4= @order.product_variant.product.brand.name
    - @order.product_variant.product.product_categories.each do |category|
      = category.category.name

    .card.showproduct
      .card-header
        Variant Details
      .card-body
        = @order.product_variant.storage.name
        ,
        = @order.product_variant.color.name
        ,
        = @order.product_variant.processor.name
        ,
        = @order.product_variant.display.name
        ,
        = @order.product_variant.weight
        gram ,
        = @order.product_variant.height
        cm ,
        = @order.product_variant.width
        cm ,
        = @order.product_variant.thickness
        mm ,
        = @order.product_variant.front_camera
        MP ,
        = @order.product_variant.rear_camera
        MP
        %br/

        .row
          .col-2
            Seller :
          .col-3
            = @order.seller.name
          .col-0
            .text-success ₹
          .col-2
            = @order.price
          .col-2
            = @order.discount
            '%
          .col-0
            .text-success ₹
          .col-2
            = @order.final_price

.container
  .card-deck
    .card
      .card-header
        User Details
      .card-body
        = current_user.name
        %br/
        = current_user.email
        %br/
        = current_user.contact_no
    .card
      .card-header
        Shipping Details
      .card-body
        = @order.address
        = @order.city
        = @order.state
        = @order.pincode

    .card
      .card-header
        Payment Details
      .card-body
        = @order.payment_type
        %br/
        = @order.payment_transaction


  %br/
  %br/
  = link_to "My Order", users_orders_path, class: "btn btn-success"

  = link_to "My Favorite", show_favorite_path, class: "btn btn-success"

  = link_to "Back", product_path, class: "btn btn-success"

:javascript
  function set_image(imgs){
    $(".hide").hide();
    var expandImg = document.getElementById("expandedImg");
    expandImg.src = imgs.src;
    expandImg.parentElement.style.display = "block";
  }

app/views/order/index.html.haml
.row
  .col-sm-5
    .card
      .row
        .col-sm-4
          .product
            - if @product.mobile_photos.attached?
              - @product.mobile_photos.each do |mobile_photo|
                .col-2
                  = image_tag(mobile_photo, size: "80", onclick: "set_image(this);",class:"list-group-item")
        .col-sm-6
          .container
            - if @product.mobile_photos.attached?
              = image_tag(@product.mobile_photos.first, style: "width:100%", class: "hide")
              %img{ id: "expandedImg" ,style: "width:100%"}

    .container
      = link_to 'Back', product_path, class: "btn btn-success"
  .col-sm-7
    %h4= @product.description
    %h4= @product.brand.name
    = @product.release_year.strftime('%B %e, %Y at %I:%M %p')
    %br/
    - @product.product_categories.each do |category|
      = category.category.name
    %br/
    - @seller_product_variant.each do |seller_product_variants|
      %strong.text-success Seller name:
      = seller_product_variants.seller_product.seller.name
      %br/
      %strong.text-success Price:
      = seller_product_variants.price
      %br/
      %strong.text-success Discount:
      = seller_product_variants.discount
      %br/
      %strong.text-success Final Price:
      = seller_product_variants.final_price


    .row
      .card.showproduct
        .card-header
          Variant Details
        .card-body
          - @seller_product_variant.each do |seller_product_variants|
            = seller_product_variants.product_variant.storage.name
            ,
            = seller_product_variants.product_variant.color.name
            ,
            = seller_product_variants.product_variant.processor.name
            ,
            = seller_product_variants.product_variant.display.name
            ,
            = seller_product_variants.product_variant.weight
            gram ,
            = seller_product_variants.product_variant.height
            cm ,
            = seller_product_variants.product_variant.width
            cm ,
            = seller_product_variants.product_variant.thickness
            mm ,
            = seller_product_variants.product_variant.front_camera
            MP ,
            = seller_product_variants.product_variant.rear_camera
            MP
            %br/
            %br/
            = link_to "Order", order_payment_path, class: "btn btn-success"



:javascript
  function set_image(imgs){
    $(".hide").hide();
    var expandImg = document.getElementById("expandedImg");
    expandImg.src = imgs.src;
    expandImg.parentElement.style.display = "block";
  }

app/views/order/payment.html.haml
.row
  .col-sm-5
    .card
      .row
        .col-sm-4
          .product
            - if @product.mobile_photos.attached?
              - @product.mobile_photos.each do |mobile_photo|
                .col-2
                  = image_tag(mobile_photo, size: "80", onclick: "set_image(this);",class:"list-group-item")
        .col-sm-6
          .container
            - if @product.mobile_photos.attached?
              = image_tag(@product.mobile_photos.first, style: "width:100%", class: "hide")
              %img{ id: "expandedImg" ,style: "width:100%"}

  .col-sm-6
    %h4= @product.description
    %h4= @product.brand.name
    = @product.release_year.strftime('%B %e, %Y at %I:%M %p')
    %br/
    - @product.product_categories.each do |category|
      = category.category.name
    %br/
    - @seller_product_variant.each do |seller_product_variants|
      %strong.text-success Seller name:
      = seller_product_variants.seller_product.seller.name
      %br/
      %strong.text-success Price:
      = seller_product_variants.price
      %br/
      %strong.text-success Discount:
      = seller_product_variants.discount
      %br/
      %strong.text-success Final Price:
      = seller_product_variants.final_price
    .row
      .card.showproduct
        .card-header
          Variant Details
        .card-body
          - @seller_product_variant.each do |seller_product_variants|
            = seller_product_variants.product_variant.storage.name
            ,
            = seller_product_variants.product_variant.color.name
            ,
            = seller_product_variants.product_variant.processor.name
            ,
            = seller_product_variants.product_variant.display.name
            ,
            = seller_product_variants.product_variant.weight
            gram ,
            = seller_product_variants.product_variant.height
            cm ,
            = seller_product_variants.product_variant.width
            cm ,
            = seller_product_variants.product_variant.thickness
            mm ,
            = seller_product_variants.product_variant.front_camera
            MP,
            = seller_product_variants.product_variant.rear_camera
            MP
.row
  .col-sm-5
    .card
      .card-header
        %h4 User Details
      .card-body
        = current_user.name
        %br/
        = current_user.email
        %br/
        = current_user.contact_no
  .col-sm-5
    .card
      .card-header
        %h4 Billing Address
      .card-body
        = form_for @order, method: 'post', url: order_path do |f|
          address
          = f.text_field :address, class: "form-control"
          %br/
          city
          = f.text_field :city, class: "form-control"
          %br/
          state
          = f.text_field :state, class: "form-control"
          %br/
          pincode
          = f.text_field :pincode, class: "form-control"
          = f.hidden_field :seller_product_variant_id
          = f.hidden_field :seller_id
          = f.hidden_field :product_variant_id
          = f.hidden_field :price
          = f.hidden_field :discount
          = f.hidden_field :final_price
          %br/
          .field
            = f.radio_button :payment_type, "cash_on_delivery"
            = f.label :cash_on_delivery, "Cash-On-Delivery"
            %br/
            = f.radio_button :payment_type, "net_banking"
            = f.label :net_banking, "Net-Banking"
            .showhide
              = f.text_field :payment_transaction, class: "form-control"
          %br/
          = f.submit "payment", class: 'btn btn-success'

.container
  = link_to "Back", order_path, class: 'btn btn-success'


:javascript
  $(function() {
    $('input[name="order[payment_type]"]').on('click', function() {
        if ($(this).val() == 'net_banking') {
            $('.showhide').show();
        }
        else {
            $('.showhide').hide();
        }
    });
  });
  function set_image(imgs){
    $(".hide").hide();
    var expandImg = document.getElementById("expandedImg");
    expandImg.src = imgs.src;
    expandImg.parentElement.style.display = "block";
  }