config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: %i[index show]

  namespace :vender do
    resources :products
    resources :orders, only: %i[index show]
  end

  namespace :users do
    resources :orders, only: %i[index show destroy]
  end
  
  get '/sellers/profile', to: 'sellers#profile', as: 'seller_profile'
  get '/users/profile',   to: 'users#profile',   as: 'user_profile'

  post '/products/:id/favorite', to: 'wishlists#index', as: 'product_favorite'
  get '/favorite', to: 'wishlists#show', as: 'show_favorite'
  delete '/favorite/:id', to: 'wishlists#destroy', as: 'destroy_favorite'

  get '/products/:id/:seller_product_variant_id/order', to: 'order#index', as: 'order'
  get '/products/:id/:seller_product_variant_id/order/payment', to: 'order#payment', as: 'order_payment'
  post '/products/:id/:seller_product_variant_id/order', to: 'order#create'
  get '/products/:id/:seller_product_variant_id/order/confirm', to: 'order#confirmation', as: 'order_payment_confirm'

  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  after_save :email_processing
  validates :address, :city, :state, :pincode, presence: true
  belongs_to :seller
  belongs_to :user
  belongs_to :seller_product_variant
  belongs_to :product_variant

  def email_processing
    OrderJob.perform_later(user_id, seller_id)
  end
end

app/controllers/order_controller.rb
# frozen_string_literal: true

# :nodoc:
class OrderController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[index payment confirmation]

  def index; end

  def payment
    @seller = SellerProductVariant.find_by(id: params[:seller_product_variant_id])
    @order = current_user.orders.new(seller_id: @seller.seller_product.seller_id, product_variant_id: @seller.product_variant_id, price: @seller.price, discount: @seller.discount, final_price: @seller.final_price, seller_product_variant_id: params[:seller_product_variant_id])
  end

  def create
    @order = current_user.orders.new(order_params)
    @order.ordered_date = Time.now
    if @order.save
      redirect_to order_payment_confirm_path
    else
      render action: 'payment'
    end
  end

  def confirmation
    @order = current_user.orders.where(seller_product_variant_id: params[:seller_product_variant_id]).last
  end

  private

  def set_order
    @product = Product.find_by(id: params[:id])
    @seller_product_variant = SellerProductVariant.where(id: params[:seller_product_variant_id])
  end

  def order_params
    params.require(:order).permit(:user_id, :seller_id,
                                  :seller_product_variant_id,
                                  :product_variant_id, :price, :discount,
                                  :final_price, :address, :city, :state,
                                  :pincode, :ordered_date, :shipping_date,
                                  :cancle_date, :payment_type,
                                  :payment_transaction)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.where(id: params[:id])
    @seller_product_variants = SellerProductVariant.where(id: params[:seller_product_variant_id])
  end

  def payment
    @products = Product.where(id: params[:id])
    @seller_product_variants = SellerProductVariant.where(id: params[:seller_product_variant_id])
    @product_variant = ProductVariant.joins(:seller_product_variants).where(seller_product_variants: { id: params[:seller_product_variant_id] })
    @seller = SellerProductVariant.find_by(params[:seller_product_variant_id])

    @order = current_user.orders.new(seller_id: @seller.seller_product.seller_id, product_variant_id: @product_variant.ids, price: @seller.price, discount: @seller.discount, final_price: @seller.final_price, seller_product_variant_id: params[:seller_product_variant_id])
  end

  def order
    @order = current_user.orders.all
  end
  def show
    @orders = Order.find_by(id: params[:id])

  end
  def create
    @order = current_user.orders.new(order_params)
    @order.ordered_date = Time.now

    if @order.save
      redirect_to order_payment_confirm_path
    else
      render action: 'payment'
    end

  end

  def confirmation
    @products = Product.where(id: params[:id])
    @seller_product_variants = SellerProductVariant.where(id: params[:seller_product_variant_id])
    @product_variant = ProductVariant.joins(:seller_product_variants).where(seller_product_variants: { id: params[:seller_product_variant_id] })
  end

  def destroy
    @order = Order.find_by(id: params[:id])
    @order.destroy
    redirect_to order_path
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :seller_id, :seller_product_variant_id, :product_variant_id, :price, :discount, :final_price, :address, :city, :state, :pincode, :ordered_date, :shipping_date, :cancle_date, :payment_type, :payment_transaction)
  end
end

app/controllers/users/orders_controller.rb
module Users
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
      @order = current_user.orders.all
    end

    def show
      @orders = Order.find_by(id: params[:id])
      @time = Time.at(@orders.ordered_date).strftime("%B %e, %Y at %I:%M %p")
    end

    def destroy
      @order = Order.find_by(id: params[:id])
      @order.destroy
      redirect_to users_orders_path
    end

    private

    def order_params
      params.require(:order).permit(:user_id, :seller_id, :seller_product_variant_id, :product_variant_id, :price, :discount, :final_price, :address, :city, :state, :pincode, :ordered_date, :shipping_date, :cancle_date, :payment_type, :payment_transaction)
    end
  end
end

app/controllers/vender/order_controller.rb
module Vender
  # :nodoc:
  class OrderController < ApplicationController
    before_action :authenticate_seller!
    def index
      @order = current_seller.orders.all
    end
  end
end

app/controllers/vender/orders_controller.rb
# frozen_string_literal: true

module Vender
  # :nodoc:
  class OrdersController < ApplicationController
    before_action :authenticate_seller!
    def index
      @order = current_seller.orders.all
    end

    def show
      @order = Order.find_by(id: params[:id])
    end
  end
end

app/controllers/vender/products_controller.rb
# frozen_string_literal: true

module Vender
  # :nodoc:
  class ProductsController < ApplicationController
    before_action :authenticate_seller!
    before_action :set_seller_product, only: %i[show edit update destroy]

    def index
      @vender_products = current_seller.seller_products.page(params[:page]).per(20)
    end

    def show; end

    def new
      @product_variant = Product.find_by(id: params[:product_id])
      @vender_product = current_seller.seller_products.new(product_id: params[:product_id])
    end

    def edit
      @product_variant = @vender_product.product
    end

    def create
      @vender_product = current_seller.seller_products.new(seller_product_params)
      respond_to do |format|
        if @vender_product.save
          format.html { redirect_to vender_products_url, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: vender_products_url }
        else
          format.html { render :new }
          format.json { render json: @vender_product.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @vender_product.update(seller_product_params)
          format.html { redirect_to vender_products_url, notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: vender_products_url }
        else
          format.html { render :edit }
          format.json { render json: @vender_product.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @vender_product.destroy
      respond_to do |format|
        format.html { redirect_to vender_products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_seller_product
      @vender_product = SellerProduct.find_by(id: params[:id])
    end

    def seller_product_params
      params.require(:seller_product).permit(:product_id, :seller_id,
                                             seller_product_variants_attributes:
                                             %i[id product_variant_id price
                                                discount final_price _destroy])
    end
  end
end

app/views/vender/orders/index.html.haml
%br/
- if @order.empty?
  .text-center
    .card
      %h5 No orders yet!
- else
  .container
    .row
      .card.showproduct
        .card-header
          My Order
        .card-body
          - @order.each do |orders|
            .row
              .col-3
                = image_tag(orders.seller_product_variant.product_variant.product.mobile_photos.first, width: "100px", height: "150px")
              .col-7
                = orders.seller_product_variant.product_variant.product.description
                %br/
                = orders.seller_product_variant.product_variant.product.brand.name
                %br/
                %strong User :
                = orders.user.name
                %br/
                %strong order date:
                = orders.ordered_date.strftime("%B %d at %I:%M %p")
              .col-2
                .icon-size
                  = link_to fa_icon("eye"),vender_order_path(orders)
              %hr/

app/views/vender/orders/show.html.haml
.row
  .col-sm-5
    .card
      .row
        .col-sm-4
          .product
            - if @order.product_variant.product.mobile_photos.attached?
              - @order.product_variant.product.mobile_photos.each do |mobile_photo|
                .col-2
                  = image_tag(mobile_photo, size: "80", onclick: "set_image(this);",class:"list-group-item")
        .col-sm-6
          .container
            - if @order.product_variant.product.mobile_photos.attached?
              = image_tag(@order.product_variant.product.mobile_photos.first, style: "width:100%", class: "hide")
              %img{ id: "expandedImg" ,style: "width:100%"}
    .container
      = link_to 'Back', vender_orders_path, class: "btn btn-success"
  .col-sm-7
    %h4= @order.product_variant.product.description
    %h4= @order.product_variant.product.brand.name
    - @order.product_variant.product.product_categories.each do |category|
      = category.category.name
    .col
      .card
        .card-header
          Variant Details
        .card-body
          = @order.product_variant.storage.name
          ,
          = @order.product_variant.color.name
          ,
          = @order.product_variant.processor.name
          ,
          = @order.product_variant.display.name
          ,
          = @order.product_variant.weight
          gram ,
          = @order.product_variant.height
          cm ,
          = @order.product_variant.width
          cm ,
          = @order.product_variant.thickness
          mm ,
          = @order.product_variant.front_camera
          MP ,
          = @order.product_variant.rear_camera
          MP
          %br/

          .row
            .col-3
              = @order.user.name
            .col-0
              .text-success ₹
            .col-2
              = @order.price
            .col-2
              = @order.discount
              '%
            .col-0
              .text-success ₹
            .col-2
              = @order.final_price

      .card-deck
        .card
          .card-header
            User Details
          .card-body
            = @order.address
            = @order.city
            = @order.state
            = @order.pincode
        .card
          .card-header
            Payment Details
          .card-body
            = @order.payment_type
            %br/
            = @order.payment_transaction



:javascript
  function set_image(imgs){
    $(".hide").hide();
    var expandImg = document.getElementById("expandedImg");
    expandImg.src = imgs.src;
    expandImg.parentElement.style.display = "block";
  }