config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: %i[index show]

  namespace :vender do
    resources :products
    resources :orders, only: %i[index show]
  end

  namespace :users do
    resources :orders, only: %i[index show destroy]
  end
  
  get '/sellers/profile', to: 'sellers#profile', as: 'seller_profile'
  get '/users/profile',   to: 'users#profile',   as: 'user_profile'

  post '/products/:id/favorite', to: 'wishlists#index', as: 'product_favorite'
  get '/favorite', to: 'wishlists#show', as: 'show_favorite'
  delete '/favorite/:id', to: 'wishlists#destroy', as: 'destroy_favorite'

  get '/products/:id/:seller_product_variant_id/order', to: 'order#index', as: 'order'
  get '/products/:id/:seller_product_variant_id/order/payment', to: 'order#payment', as: 'order_payment'
  post '/products/:id/:seller_product_variant_id/order', to: 'order#create'
  get '/products/:id/:seller_product_variant_id/order/confirm', to: 'order#confirmation', as: 'order_payment_confirm'

  root to: 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/color.rb
class Color < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :product_variants, dependent: :destroy
  has_many :products, through: :product_variants

end

app/models/display.rb
class Display < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :product_variants, dependent: :destroy
  has_many :products, through: :product_variants
end

app/models/imported_file.rb
class ImportedFile < ApplicationRecord
  after_create :file_processing

  def file_processing
    ImportedFileJob.perform_later id
  end
end

app/models/order.rb
class Order < ApplicationRecord
  after_save :email_processing
  validates :address, :city, :state, :pincode, presence: true
  belongs_to :seller
  belongs_to :user
  belongs_to :seller_product_variant
  belongs_to :product_variant

  def email_processing
    OrderJob.perform_later(user_id, seller_id)
  end
end

app/models/processor.rb
class Processor < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :product_variants, dependent: :destroy
  has_many :products, through: :product_variants
end

app/models/product.rb
class Product < ApplicationRecord
  validates :description, :available, presence: true
  belongs_to :brand
  has_many :product_variants
  has_many :colors, through: :product_variants
  has_many :displays, through: :product_variants
  has_many :processors, through: :product_variants
  has_many :storages, through: :product_variants

  has_many :product_categories, dependent: :delete_all
  has_many :categories, through: :product_categories

  has_many :seller_products
  has_many :sellers, through: :seller_products
  has_many :wishlists
  has_many_attached :mobile_photos
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :product, optional: true
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :storage, optional: true
  belongs_to :color, optional: true
  belongs_to :display, optional: true
  belongs_to :processor, optional: true
  has_many :seller_product_variants
  has_many :orders

  def name
    "#{try(:color).try(:name)} - #{try(:storage).try(:name)} - #{try(:display).try(:name)} - #{try(:processor).try(:name)}"
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :name, :address, :contact_no, presence: true
  validates :email, uniqueness: true
  validates :contact_no, numericality: true, length: { maximum: 15 }, uniqueness: true

  has_many :orders, dependent: :destroy

  has_many :seller_products, dependent: :destroy
  has_many :products, through: :seller_products

  has_one_attached :profile_photo
end

app/models/seller_product.rb
class SellerProduct < ApplicationRecord
  validates :seller_id, uniqueness: { scope: :product_id, message: 'This product already exists.' }

  belongs_to :seller
  belongs_to :product

  has_many :seller_product_variants, inverse_of: :seller_product, dependent: :destroy
  accepts_nested_attributes_for :seller_product_variants, allow_destroy: true, reject_if: :all_blank
end

app/models/storage.rb
class Storage < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :product_variants, dependent: :destroy
  has_many :products, through: :product_variants
end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :name, :address, :contact_no, presence: true
  validates :email, uniqueness: true
  validates :contact_no, numericality: true, length: { maximum: 15 }, uniqueness: true

  has_many :orders, dependent: :destroy
  has_many :wishlists, dependent: :destroy

  has_one_attached :profile_photo
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  validates :user_id, uniqueness: { scope: :product_id, message: 'This product already exists.' }

  belongs_to :user
  belongs_to :product
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# :nodoc:
class HomeController < ApplicationController
  def index
    @products = Product.joins(:brand).where(release_year: Time.current.beginning_of_month..Time.current.end_of_month).order(:description).page(params[:page]).per(4)
  end
end

app/controllers/order_controller.rb
# frozen_string_literal: true

# :nodoc:
class OrderController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[index payment confirmation]

  def index; end

  def payment
    @seller = SellerProductVariant.find_by(id: params[:seller_product_variant_id])
    @order = current_user.orders.new(seller_id: @seller.seller_product.seller_id, product_variant_id: @seller.product_variant_id, price: @seller.price, discount: @seller.discount, final_price: @seller.final_price, seller_product_variant_id: params[:seller_product_variant_id])
  end

  def create
    @order = current_user.orders.new(order_params)
    @order.ordered_date = Time.now
    if @order.save
      redirect_to order_payment_confirm_path
    else
      render action: 'payment'
    end
  end

  def confirmation
    @order = current_user.orders.where(seller_product_variant_id: params[:seller_product_variant_id]).last
  end

  private

  def set_order
    @product = Product.find_by(id: params[:id])
    @seller_product_variant = SellerProductVariant.where(id: params[:seller_product_variant_id])
  end

  def order_params
    params.require(:order).permit(:user_id, :seller_id,
                                  :seller_product_variant_id,
                                  :product_variant_id, :price, :discount,
                                  :final_price, :address, :city, :state,
                                  :pincode, :ordered_date, :shipping_date,
                                  :cancle_date, :payment_type,
                                  :payment_transaction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mobile
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.fixed-top.navbar-expand-sm.bg-dark.navbar-dark
      %a.navbar-brand
        %strong.title Mobilestore
      %ul.navbar-nav
        - if user_signed_in?
          %li.nav-item
            = link_to 'Product', products_path, class: "nav-link"
          %li.nav-item
            = link_to 'My Order', users_orders_path, class: "nav-link"
          %li.nav-item
            = link_to 'My Favorite', show_favorite_path, class: "nav-link"
          %li.nav-item
            = link_to 'Profile', user_profile_path, class: "nav-link"
          %li.nav-item
            = link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"
          .form-horizontal
            = form_tag products_path, method: 'get',class: 'form-inline' do
              = text_field_tag :search, params[:search], placeholder: 'Search', class: "form-control"
              %span.input-group-btn
                = submit_tag "Search", class: 'btn btn-success'
        - elsif seller_signed_in?
          %li.nav-item
            = link_to 'Product', vender_products_path, class: "nav-link"
          %li.nav-item
            = link_to 'Add product', new_vender_product_path, class: "nav-link"
          %li.nav-item
            = link_to 'Order', vender_orders_path, class: "nav-link"
          %li.nav-item
            = link_to 'Profile', seller_profile_path, class: "nav-link"
          %li.nav-item
            = link_to "Logout", destroy_seller_session_path, method: :delete, class: "nav-link"
        - else
          %li.nav-item
            .searchbar
              = form_tag products_path, method: 'get',class: 'form-inline' do
                = text_field_tag :search, params[:search], placeholder: 'Search', class: "form-control"
                %span.input-group-btn
                  = submit_tag t('common.search'), class: 'btn btn-success'
          %li.nav-item
            = link_to "Gujarati", {:locale => 'gu'}, class: "nav-link"
          %li.nav-item
            = link_to "English", {:locale => 'en'}, class: "nav-link"
          %li.nav-item
            .signin
              = link_to t('common.signin'), "#sign-in", class: "nav-link", "data-toggle" => "modal"
              %div{ id: "sign-in", class: "modal fade"}
                .modal-dialog
                  .modal-content
                    .modal-header
                      .modal-title
                        Sign In
                    .modal-body
                      = link_to "User Sign In", new_user_session_path, class: "btn btn-success"
                      = link_to "Seller Sign In", new_seller_session_path, class: "btn btn-success"

          %li.nav-item
            .signup
              = link_to t('common.signup'), "#sign-up", class: "nav-link", "data-toggle" => "modal"
              .modal#sign-up
                .modal-dialog
                  .modal-content
                    .modal-header
                      .modal-title
                        Sign up
                    .modal-body
                      = link_to "User Sign up", new_user_registration_path, class: "btn btn-success"
                      = link_to "Seller Sign up", new_seller_registration_path, class: "btn btn-success"



    %br/
    %br/
    = yield
    %hr
    .footer
      %footer copyright @ mobileshop 2018